### ISSUE TITLE
npm run build creates 2 .js files.

### ISSUE THREAD

**Issue by indikaUih** [jkanchelov/pixi-typescript-boilerplate#511]
Thanks for creating this boilerplate.
I have an issue when bundling files for production build.

npm run build command creates 2 .js files. I want to bundle everything into single .js file.
Can you please help to achieve this ?

Thanks in advance.

**Comment by jkanchelov** [comment]
Hey @indikaUih.  If you want to remove the code splitting you can go for it by removing 

  `   optimization: {
            splitChunks: {
                chunks: "all",
            },
        },`
 
inside webpack.config.ts.

**Comment by indikaUih** [comment]
> Hey @indikaUih. If you want to remove the code splitting you can go for it by removing
> 
> ` optimization: { splitChunks: { chunks: "all", }, },`
> 
> inside webpack.config.ts.

Worked !!!! Thanks very much.
